Hello rails react review
akezeth/hello-rails-react pull request #1
Opened 2023-10-23 14:01 UTC by akezeth

2023-10-23 19:47 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle:

Hi @akezeth, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  Implemented some project requirements. :heavy_check_mark: 
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct Gitflow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-23 19:47 UTC, Qoosim commented on app/javascript/components/Greeting.js
> +	const dispatch = useDispatch();
- [ ] Great job so far. However, there's spelling error with this file name. This file name was named `grettingsSlice.js` but was referenced here as `greetingsSlice.js`. Kindly correct that.

### Spelling mistake
![greetings-error](https://github.com/akezeth/hello-rails-react/assets/26597432/61e695ba-af59-4071-a2fa-dc81785dc4c3)

2023-10-23 19:47 UTC, Qoosim commented on app/javascript/redux/store.js
> +import messagesreducer from './greetings/greetingsSlice';
- [ ] Same thing here too :point_down: 


![store-err](https://github.com/akezeth/hello-rails-react/assets/26597432/e9eea7b8-022d-4bac-8933-ca7aaf68c719)

2023-10-23 19:47 UTC, Qoosim commented on config/routes.rb
> +end
- [ ] You might need to look into this route too. This route only generates this message alone, not random messages I created.

### For `http://127.0.0.1:3000/greetings/index`
![msg-1](https://github.com/akezeth/hello-rails-react/assets/26597432/fc2b7e94-b803-465e-a6c9-c47c1099d32b)

### For `http://127.0.0.1:3000/greetings`

![msg-2](https://github.com/akezeth/hello-rails-react/assets/26597432/26f393c4-88cc-4de5-8bdd-7b1bed54979b)

### For `http://127.0.0.1:3000`

![loading](https://github.com/akezeth/hello-rails-react/assets/26597432/680fa033-5cb3-4aa3-aa79-87c9296fc729)

2023-10-24 05:57 UTC, DammyShittu approved these changes
Hi @akezeth,

## APPROVED 🟢

## Highlights
✔️ Project met all technical requirements

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-24 16:07 UTC, merged